[package]
name = "state-pattern"
version = "0.1.0"
authors = ["Nov11 <529079634@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
